-- Zones de rapprochement : chaque localité du relevé de tonnage rattachée à la
-- zone du contrat la plus proche (métier, 3 octobre 2026 : « la zone de
-- rapprochement proche de la zone contractuelle »).
--
-- Proposition à valider par l'exploitation : ce qui est incertain le dit
-- (« à confirmer »). Une localité composée (« KM/BENT ») n'a pas besoin de
-- ligne : l'application la facture à la plus chère de ses parties. Restent
-- sans rattachement, et signalées dans le rapport : ce qui n'est pas un lieu
-- (fermes REPRO, « EN FACE », « Non précisée ») et les lieux non reconnus
-- (APRAM, THOR, HANENE, VISSENE, K YAKHAM, KMBIR, KARAONIE, PA…).
--
-- Rejouable : une localité déjà rattachée garde son rattachement.

insert into rattachement_localite (localite_normalisee, localite, destination, origine, motif) values
  ('THIES', 'THIES', 'Thiès', 'usage', 'Zone du contrat (proposition du 3 octobre 2026)'),
  ('TOUBA', 'TOUBA', 'Touba', 'usage', 'Zone du contrat ; Mbacké jouxte Touba (proposition du 3 octobre 2026)'),
  ('MBACKE', 'MBACKE', 'Touba', 'usage', 'Zone du contrat ; Mbacké jouxte Touba (proposition du 3 octobre 2026)'),
  ('NDAMLO', 'NDAMLO', 'Touba', 'usage', 'Zone du contrat ; Mbacké jouxte Touba (proposition du 3 octobre 2026)'),
  ('MBOUR', 'MBOUR', 'Mbour', 'usage', 'Zone du contrat, ou sa petite côte (proposition du 3 octobre 2026)'),
  ('JOAL', 'JOAL', 'Mbour', 'usage', 'Zone du contrat, ou sa petite côte (proposition du 3 octobre 2026)'),
  ('LOULI', 'LOULI', 'Mbour', 'usage', 'Zone du contrat, ou sa petite côte (proposition du 3 octobre 2026)'),
  ('MBODJENE', 'MBODJENE', 'Mbour', 'usage', 'Zone du contrat, ou sa petite côte (proposition du 3 octobre 2026)'),
  ('SINDIA', 'SINDIA', 'Mbour', 'usage', 'Zone du contrat, ou sa petite côte (proposition du 3 octobre 2026)'),
  ('KAOLACK', 'KAOLACK', 'Kaolack', 'usage', 'Zone du contrat, ou bassin de Kaolack-Fatick (proposition du 3 octobre 2026)'),
  ('FATICK', 'FATICK', 'Kaolack', 'usage', 'Zone du contrat, ou bassin de Kaolack-Fatick (proposition du 3 octobre 2026)'),
  ('PASSY', 'PASSY', 'Kaolack', 'usage', 'Zone du contrat, ou bassin de Kaolack-Fatick (proposition du 3 octobre 2026)'),
  ('POROKHANE', 'POROKHANE', 'Kaolack', 'usage', 'Zone du contrat, ou bassin de Kaolack-Fatick (proposition du 3 octobre 2026)'),
  ('LOUGA', 'LOUGA', 'Louga', 'usage', 'Zone du contrat, ou axe de Louga (proposition du 3 octobre 2026)'),
  ('GUEOUL', 'GUEOUL', 'Louga', 'usage', 'Zone du contrat, ou axe de Louga (proposition du 3 octobre 2026)'),
  ('NOTTO', 'NOTTO', 'Notto', 'usage', 'Zone du contrat, ou axe Bayakh-Notto (proposition du 3 octobre 2026)'),
  ('NOTTO 2', 'NOTTO 2', 'Notto', 'usage', 'Zone du contrat, ou axe Bayakh-Notto (proposition du 3 octobre 2026)'),
  ('BAYAKH', 'BAYAKHµ', 'Notto', 'usage', 'Zone du contrat, ou axe Bayakh-Notto (proposition du 3 octobre 2026)'),
  ('KAYAR', 'KAYAR', 'Notto', 'usage', 'Zone du contrat, ou axe Bayakh-Notto (proposition du 3 octobre 2026)'),
  ('NGAYE', 'NGAYE', 'Ngaye', 'usage', 'Ngaye Mékhé, zone du contrat (proposition du 3 octobre 2026)'),
  ('NGAYE MKH', 'NGAYE MKH', 'Ngaye', 'usage', 'Ngaye Mékhé, zone du contrat (proposition du 3 octobre 2026)'),
  ('POTOU', 'POTOU', 'Potou', 'usage', 'Zone du contrat (proposition du 3 octobre 2026)'),
  ('ST LOUISAB', 'ST LOUISAB', 'Saint-Louis', 'usage', 'Saint-Louis, ou Ross Béthio (40 km de Saint-Louis) (proposition du 3 octobre 2026)'),
  ('ROSS BET', 'ROSS BET', 'Saint-Louis', 'usage', 'Saint-Louis, ou Ross Béthio (40 km de Saint-Louis) (proposition du 3 octobre 2026)'),
  ('ROSE BETHIO', 'ROSE BETHIO', 'Saint-Louis', 'usage', 'Saint-Louis, ou Ross Béthio (40 km de Saint-Louis) (proposition du 3 octobre 2026)'),
  ('ROSSE BETH', 'ROSSE BETH', 'Saint-Louis', 'usage', 'Saint-Louis, ou Ross Béthio (40 km de Saint-Louis) (proposition du 3 octobre 2026)'),
  ('ROSS BETHIO', 'ROSS BETHIO', 'Saint-Louis', 'usage', 'Saint-Louis, ou Ross Béthio (40 km de Saint-Louis) (proposition du 3 octobre 2026)'),
  ('FOUND', 'FOUND', 'Foundiougne', 'usage', 'Abréviation de Foundiougne (proposition du 3 octobre 2026)'),
  ('FOUDIOUNE', 'FOUDIOUNE', 'Foundiougne', 'usage', 'Abréviation de Foundiougne (proposition du 3 octobre 2026)'),
  ('TIVAONE', 'TIVAONE', 'Tivaouane', 'usage', 'Tivaouane, son département, ou Tivaouane Peulh comme TIV PEUL (proposition du 3 octobre 2026)'),
  ('TAIBA', 'TAIBA', 'Tivaouane', 'usage', 'Tivaouane, son département, ou Tivaouane Peulh comme TIV PEUL (proposition du 3 octobre 2026)'),
  ('DIOGO', 'DIOGO', 'Tivaouane', 'usage', 'Tivaouane, son département, ou Tivaouane Peulh comme TIV PEUL (proposition du 3 octobre 2026)'),
  ('T PEUL', 'T PEUL', 'Tivaouane', 'usage', 'Tivaouane, son département, ou Tivaouane Peulh comme TIV PEUL (proposition du 3 octobre 2026)'),
  ('TIVPEUL', 'TIVPEUL', 'Tivaouane', 'usage', 'Tivaouane, son département, ou Tivaouane Peulh comme TIV PEUL (proposition du 3 octobre 2026)'),
  ('TTIV PEUL', 'TTIV PEUL', 'Tivaouane', 'usage', 'Tivaouane, son département, ou Tivaouane Peulh comme TIV PEUL (proposition du 3 octobre 2026)'),
  ('TIV PEUL', 'TIV/PEUL', 'Tivaouane', 'usage', 'Tivaouane, son département, ou Tivaouane Peulh comme TIV PEUL (proposition du 3 octobre 2026)'),
  ('GOROM 1', 'GOROM 1', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('GOROM 3', 'GOROM 3', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('GOROM1', 'GOROM1', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('GOROM3', 'GOROM3', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('GORM', 'GORM', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('NOFLAY', 'NOFLAY', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('KM', 'KM', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('KEUR MA', 'KEUR MA', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('DIAMNIADIO', 'DIAMNIADIO', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('THIAROY', 'THIAROY', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('THIROYE', 'THIROYE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('BAM', 'BAM', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('BAMB', 'BAMB', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('BMBLOR', 'BMBLOR', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('BBLOR', 'BBLOR', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('DENE', 'DENE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('DENNE', 'DENNE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('YENNE', 'YENNE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('YENE', 'YENE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('SEBI', 'SEBI', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('MALEIKA', 'MALEIKA', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('LAC ROSE', 'LAC ROSE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('GUEDIAWAYE', 'GUEDIAWAYE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('GUEDIAWAY', 'GUEDIAWAY', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('GW', 'GW', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('YEUM', 'YEUM', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('YEUMBL', 'YEUMBL', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('YEMB', 'YEMB', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('JAAXAY', 'JAAXAY', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('JAXAAY', 'JAXAAY', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('SANGLKM', 'SANGLKM', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('SNGLKM', 'SNGLKM', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('SGKM', 'SGKM', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('SAGKM', 'SAGKM', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('SANGALKM', 'SANGALKM', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('SANGAL', 'SANGAL', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('CAMBERENE', 'CAMBERENE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('CAMB', 'CAMB', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('COLOBANE', 'COLOBANE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('APIX', 'APIX', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('SANDAGA', 'SANDAGA', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('ASECNA', 'ASECNA', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('MBAO', 'MBAO', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('ZAC MBAO', 'ZAC MBAO', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('DIAMAGUEN', 'DIAMAGUEN', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('POMPIER', 'POMPIER', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('NIKHIRATE', 'NIKHIRATE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('BARGNY', 'BARGNY', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('RUFISQUE', 'RUFISQUE', 'Dakar', 'usage', 'Région de Dakar et département de Rufisque, tarif urbain (KM = Keur Massar, SGKM = Sangalkam, BAM = Bambilor) (proposition du 3 octobre 2026)'),
  ('BENTEIGNE', 'BENTEIGNE', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('BENTENIER', 'BENTENIER', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('BANDIAN', 'BANDIAN', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('POUT DIACK', 'POUT DIACK', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('POUTDIAC', 'POUTDIAC', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('DOUGAR TRS', 'DOUGAR TRS', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('NDOYENNE', 'NDOYENNE', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('NDOYEN', 'NDOYEN', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('NIACLRP', 'NIACLRP', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('NIACOURP', 'NIACOURP', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('NGOUDIANE', 'NGOUDIANE', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('KMOUSSEU', 'KMOUSSEU', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('KMOUSSA', 'KMOUSSA', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('K MOUSSA', 'K MOUSSA', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('K MATAR', 'K MATAR', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('KMATAR', 'KMATAR', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('KEUR MATAR', 'KEUR MATAR', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('TASSETTE', 'TASSETTE', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('NDIGUENE', 'NDIGUENE', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('NIEGUENE', 'NIEGUENE', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('NGIEGUENE', 'NGIEGUENE', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('NDIEGENE', 'NDIEGENE', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('DIEGUEN', 'DIEGUEN', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('KHOMBOL', 'KHOMBOL', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('WAYE', 'WAYE', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('NDIAR', 'NDIAR', 'Thiès', 'usage', 'Département de Thiès, comme les localités voisines déjà rattachées (proposition du 3 octobre 2026)'),
  ('KM50', 'KM50', 'Thiès', 'usage', 'Km 50 de la nationale, à hauteur de Pout — à confirmer (proposition du 3 octobre 2026)'),
  ('KM 50', 'KM 50', 'Thiès', 'usage', 'Km 50 de la nationale, à hauteur de Pout — à confirmer (proposition du 3 octobre 2026)'),
  ('DIOURBEL', 'DIOURBEL', 'Touba', 'usage', 'Plus près de Touba (45 km) que de Thiès (75 km) — à confirmer (proposition du 3 octobre 2026)'),
  ('NGOYE', 'NGOYE', 'Thiès', 'usage', 'Ngoye (Bambey), plus près de Thiès que de Touba — à confirmer (proposition du 3 octobre 2026)'),
  ('DIOUROUP', 'DIOUROUP', 'Kaolack', 'usage', 'Diouroup (Fatick), plus près de Kaolack que de Mbour — à confirmer (proposition du 3 octobre 2026)'),
  ('MBAWANE', 'MBAWANE', 'Notto', 'usage', 'Entre Kayar et Notto — à confirmer (proposition du 3 octobre 2026)'),
  ('DIENDER', 'DIENDER', 'Notto', 'usage', 'Entre Kayar et Notto — à confirmer (proposition du 3 octobre 2026)'),
  ('DAGA', 'DAGA', 'Notto', 'usage', 'Entre Kayar et Notto — à confirmer (proposition du 3 octobre 2026)'),
  ('DAGAKHOLP', 'DAGAKHOLP', 'Notto', 'usage', 'Entre Kayar et Notto — à confirmer (proposition du 3 octobre 2026)'),
  ('DAGA KHPA', 'DAGA KHPA', 'Notto', 'usage', 'Entre Kayar et Notto — à confirmer (proposition du 3 octobre 2026)'),
  ('NGENIENE', 'NGENIENE', 'Mbour', 'usage', 'Plus près de Mbour que des autres zones du contrat — à confirmer (proposition du 3 octobre 2026)'),
  ('T DIALAW', 'T DIALAW', 'Mbour', 'usage', 'Plus près de Mbour que des autres zones du contrat — à confirmer (proposition du 3 octobre 2026)'),
  ('FIMLA', 'FIMLA', 'Mbour', 'usage', 'Plus près de Mbour que des autres zones du contrat — à confirmer (proposition du 3 octobre 2026)'),
  ('DIASS', 'DIASS', 'Mbour', 'usage', 'Plus près de Mbour que des autres zones du contrat — à confirmer (proposition du 3 octobre 2026)'),
  ('SINDIAN', 'SINDIAN', 'Mbour', 'usage', 'Plus près de Mbour que des autres zones du contrat — à confirmer (proposition du 3 octobre 2026)')
on conflict (localite_normalisee) do nothing;
