-- ============================================================================
-- SEDIMA Parc — le catalogue des tâches de service, tiré de l'export Fleetio.
--
-- **Ce n'est pas une migration.** À jouer après 0060. Fabriqué par
-- `scripts/charger-taches-fleetio.mts` — voir docs/SERVICES-MAINTENANCE.md.
--
-- 510 tâches dans l'export ; 160 jamais utilisées, laissées ; 4 qui ne sont pas des
-- tâches (main-d'œuvre, « maintenance curative »…), écartées ; 5 doublons fondus.
-- Restent **341 tâches**, classées comme Fleetio (catégorie, système, ensemble),
-- 26 à classer. Leurs utilisations dans Fleetio ordonnent les listes.
--
-- REJOUABLE : une tâche dont le libellé existe déjà n'est pas recréée.
-- ============================================================================

insert into tache_service (numero, libelle, description, categorie, systeme, ensemble, type_defaut, alias, utilisations, source, a_classer) values
  ('TCH-2026-00001', 'Remplacement de l''huile moteur et du filtre', 'Remplacement de l''huile moteur et du filtre pour assurer une lubrification adéquate du moteur.', '4', '045', '011', 'preventif', array['vidange']::text[], 1413, 'fleetio', false),
  ('TCH-2026-00002', 'Carrosserie (Divers)', 'Divers travaux liés à la carrosserie.', '0', '002', null, 'curatif', array['Carrosserie et châssis (Divers)']::text[], 1288, 'fleetio', false),
  ('TCH-2026-00003', 'Pneus (Divers)', 'Divers travaux ou vérifications liés aux pneus non spécifiés.', '1', '017', null, 'curatif', '{}'::text[], 728, 'fleetio', false),
  ('TCH-2026-00004', 'Moteur (Divers)', 'Réparations et ajustements divers du moteur.', '4', null, null, 'curatif', '{}'::text[], 439, 'fleetio', false),
  ('TCH-2026-00005', 'Accessoires/Aménagements (Divers)', 'Réparations et ajustements divers des accessoires et équipements du véhicule.', '5', null, null, 'curatif', '{}'::text[], 353, 'fleetio', false),
  ('TCH-2026-00006', 'Freins (Divers)', 'Réparations et ajustements divers des systèmes de freinage.', '1', '013', null, 'curatif', '{}'::text[], 268, 'fleetio', false),
  ('TCH-2026-00007', 'Transmission (Divers)', 'Divers travaux ou vérifications liés à la transmission automatique non spécifiés.', '2', null, null, 'curatif', '{}'::text[], 260, 'fleetio', false),
  ('TCH-2026-00008', 'Remplacement Feux arrières, stop, clignotants ou plaque', null, '3', '034', '002', 'curatif', '{}'::text[], 256, 'fleetio', false),
  ('TCH-2026-00009', 'Remplacement de la batterie', 'Remplacement de la batterie pour garantir un démarrage fiable et une alimentation électrique adéquate.', '3', '032', '001', 'curatif', '{}'::text[], 236, 'fleetio', false),
  ('TCH-2026-00010', 'Remplacement de la bobine d''allumage', 'Remplacement de la bobine d''allumage pour une étincelle moteur fiable.', '3', '033', '003', 'curatif', '{}'::text[], 202, 'fleetio', false),
  ('TCH-2026-00011', 'Remplacement des pneus', 'Remplacement des pneus usés ou endommagés pour assurer une conduite sûre.', '1', '017', '001', 'curatif', '{}'::text[], 191, 'fleetio', false),
  ('TCH-2026-00012', 'Inspection de l''ensemble d''embrayage', 'Vérification de l''ensemble d''embrayage pour s''assurer qu''il fonctionne correctement et sans glissement.', '2', '023', '002', 'preventif', '{}'::text[], 189, 'fleetio', false),
  ('TCH-2026-00013', 'Frais administratifs/divers', 'Coûts ou tâches administratifs et divers travaux et services liés à la gestion du véhicule.', '9', '999', '999', 'curatif', '{}'::text[], 173, 'fleetio', false),
  ('TCH-2026-00014', 'Lavage du véhicule', 'Nettoyage complet du véhicule pour maintenir son apparence et éviter l''accumulation de saleté.', '9', '999', '999', null, '{}'::text[], 151, 'fleetio', false),
  ('TCH-2026-00015', 'Remplacement de l''assemblage d''embrayage', 'Remplacement de l''assemblage d''embrayage pour assurer un fonctionnement optimal du système d''embrayage.', '2', '023', '002', 'curatif', '{}'::text[], 144, 'fleetio', false),
  ('TCH-2026-00016', 'Remplacement du disque d''embrayage', 'Remplacement du disque d''embrayage pour assurer une connexion fluide entre le moteur et la transmission.', '2', '023', '002', 'curatif', '{}'::text[], 125, 'fleetio', false),
  ('TCH-2026-00017', 'Assistance routière/remorquage', 'Assistance en cas de panne ou de besoin de remorquage sur la route.', '9', '999', '999', 'curatif', array['MAIN D OEUVRE DEPANNAGE']::text[], 122, 'fleetio', false),
  ('TCH-2026-00018', 'Remplacement du filtre à carburant', 'Remplacement du filtre à carburant pour assurer une alimentation en carburant propre.', '4', '044', '002', 'preventif', '{}'::text[], 105, 'fleetio', false),
  ('TCH-2026-00019', 'Remplacement des plaquettes de frein', 'Remplacement des plaquettes de frein pour maintenir une puissance de freinage optimale.', '1', '013', '017', 'curatif', '{}'::text[], 94, 'fleetio', false),
  ('TCH-2026-00020', 'Inspection du système d''allumage', 'Vérification du système d''allumage pour assurer un démarrage fiable et un bon fonctionnement.', '3', '033', null, 'preventif', '{}'::text[], 89, 'fleetio', false),
  ('TCH-2026-00021', 'Remplacement de l''ensemble de transmission', 'Remplacement de l''ensemble de transmission pour résoudre les problèmes de changement de vitesse.', '2', '026', '001', 'curatif', '{}'::text[], 83, 'fleetio', false),
  ('TCH-2026-00022', 'Remplacement de l''interrupteur d''allumage', 'Remplacement de l''interrupteur d''allumage pour résoudre les problèmes de démarrage du véhicule.', '3', '033', '001', 'curatif', '{}'::text[], 79, 'fleetio', false),
  ('TCH-2026-00023', 'Remplacement de la Pompe à Eau', 'Remplacement de la pompe à eau pour assurer une circulation adéquate du liquide de refroidissement.', '4', '042', '004', 'curatif', '{}'::text[], 77, 'fleetio', false),
  ('TCH-2026-00024', 'Service de batterie', 'Service de vérification et d''entretien de la batterie pour garantir son bon état de fonctionnement.', '3', '032', '001', 'preventif', '{}'::text[], 73, 'fleetio', false),
  ('TCH-2026-00025', 'Châssis (Divers)', 'Réparations et ajustements divers du châssis du véhicule.', '1', '014', null, 'curatif', '{}'::text[], 65, 'fleetio', false),
  ('TCH-2026-00026', 'Freins arrière et tambours', 'Vérification ou remplacement des freins arrière et des tambours pour maintenir une performance de freinage adéquate.', '1', '013', '002', null, '{}'::text[], 65, 'fleetio', false),
  ('TCH-2026-00027', 'Carburant (Divers)', 'Entretien général lié au carburant, incluant les vérifications et les ajustements divers.', '4', '044', null, 'curatif', '{}'::text[], 59, 'fleetio', false),
  ('TCH-2026-00028', 'Pneus/Roue (Divers)', 'Divers travaux ou vérifications liés aux pneus et roues non spécialisés.', '1', '017', null, 'curatif', '{}'::text[], 56, 'fleetio', false),
  ('TCH-2026-00029', 'Inspection du niveau d''huile du moteur', 'Vérification du niveau d''huile pour éviter les problèmes de lubrification.', '5', '053', '999', 'preventif', '{}'::text[], 54, 'fleetio', false),
  ('TCH-2026-00030', 'Inspection de l''éclairage extérieur', 'Vérification des lumières extérieures pour assurer une visibilité adéquate.', '3', '034', null, 'preventif', '{}'::text[], 51, 'fleetio', false),
  ('TCH-2026-00031', 'Remplacement des ampoules extérieures', 'Remplacement des ampoules extérieures pour maintenir la visibilité et la sécurité du véhicule.', '3', '034', '004', 'curatif', '{}'::text[], 50, 'fleetio', false),
  ('TCH-2026-00032', 'Remplacement de la cartouche de dessiccant du sécheur d''air', 'Remplacement de la cartouche de dessiccant pour assurer l''efficacité du sécheur d''air.', '1', '013', '010', 'curatif', '{}'::text[], 49, 'fleetio', false),
  ('TCH-2026-00033', 'Echappement/Emissions (Divers)', 'Réparations et ajustements divers du système d''échappement et des émissions.', '4', '043', null, 'curatif', '{}'::text[], 48, 'fleetio', false),
  ('TCH-2026-00034', 'Remplacement de l''ampoule de phare avant', 'Remplacement de l''ampoule du phare avant pour assurer une visibilité nocturne.', '3', '034', '004', 'curatif', '{}'::text[], 45, 'fleetio', false),
  ('TCH-2026-00035', 'Inspection de la batterie', 'Vérification de l''état de la batterie pour s''assurer de son bon fonctionnement.', '3', '032', '001', 'preventif', '{}'::text[], 42, 'fleetio', false),
  ('TCH-2026-00036', 'appareil air', null, '1', '013', null, null, '{}'::text[], 41, 'fleetio', false),
  ('TCH-2026-00037', 'Couple du système de suspension', 'Vérification et ajustement du couple des composants du système de suspension pour une fixation correcte.', '1', '016', null, null, '{}'::text[], 41, 'fleetio', false),
  ('TCH-2026-00038', 'Système électrique (Divers)', null, '3', null, null, 'curatif', array['Electrical System (Miscellaneous)']::text[], 41, 'fleetio', false),
  ('TCH-2026-00039', 'Suspension (Divers)', 'Réparations et ajustements divers du système de suspension.', '1', '016', null, 'curatif', '{}'::text[], 39, 'fleetio', false),
  ('TCH-2026-00040', 'Maintenance périodique', null, '9', '999', null, null, '{}'::text[], 38, 'fleetio', true),
  ('TCH-2026-00041', 'Remplacement des roulements de roue', 'Remplacement des roulements de roue pour garantir une performance optimale et une conduite fluide.', '1', '018', '005', 'curatif', '{}'::text[], 38, 'fleetio', false),
  ('TCH-2026-00042', 'Inspection de la vitesse au ralenti', 'Vérification de la vitesse au ralenti du moteur pour assurer un fonctionnement stable.', '4', '045', '021', 'preventif', '{}'::text[], 34, 'fleetio', false),
  ('TCH-2026-00043', 'Remplacement du filtre à air du moteur', 'Remplacement du filtre à air du moteur pour maintenir une bonne circulation d''air et une performance optimale.', '4', '041', '001', 'preventif', '{}'::text[], 34, 'fleetio', false),
  ('TCH-2026-00044', 'Entretien Préventive', 'ENtretien périodique des véhicules du HUB', '9', '999', null, 'preventif', '{}'::text[], 32, 'fleetio', true),
  ('TCH-2026-00045', 'Couple du système de suspension arrière', 'Vérification et ajustement du couple des composants du système de suspension arrière pour une fixation correcte.', '1', '016', '023', null, '{}'::text[], 31, 'fleetio', false),
  ('TCH-2026-00046', 'Inspection du radiateur', 'Vérification du radiateur pour détecter les fuites ou les obstructions.', '4', '042', '002', 'preventif', '{}'::text[], 31, 'fleetio', false),
  ('TCH-2026-00047', 'FILTRE A HUILE', null, '4', '045', null, 'preventif', '{}'::text[], 29, 'fleetio', false),
  ('TCH-2026-00048', 'FILTRE A GASOIL', null, '4', '044', null, 'preventif', '{}'::text[], 27, 'fleetio', false),
  ('TCH-2026-00049', 'GONFLAGE PNEU', null, '1', '017', null, null, '{}'::text[], 25, 'fleetio', false),
  ('TCH-2026-00050', 'Vidange et remplissage du liquide de refroidissement du moteur', 'Vidange du liquide de refroidissement et remplissage pour assurer une température de fonctionnement adéquate.', '4', '042', '002', 'preventif', '{}'::text[], 25, 'fleetio', false),
  ('TCH-2026-00051', 'Inspection des fuites moteur', 'Vérification du moteur pour détecter les fuites d''huile ou autres liquides.', '4', '045', '020', 'preventif', '{}'::text[], 23, 'fleetio', false),
  ('TCH-2026-00052', 'Remplacement du joint de culasse', 'Remplacement du joint de culasse pour éviter les fuites de liquide de refroidissement et assurer une bonne compression.', '4', '045', '007', 'curatif', '{}'::text[], 23, 'fleetio', false),
  ('TCH-2026-00053', 'Huile pour engreanages', null, '9', '999', null, 'preventif', '{}'::text[], 22, 'fleetio', true),
  ('TCH-2026-00054', 'Inspection des roulements de roue', 'Vérification des roulements de roue pour détecter tout signe d''usure ou de dommage.', '1', '018', '005', 'preventif', '{}'::text[], 22, 'fleetio', false),
  ('TCH-2026-00055', 'Remplacement de la pompe à carburant', 'Remplacement de la pompe à carburant défaillante pour assurer un approvisionnement adéquat en carburant.', '4', '044', '003', 'curatif', '{}'::text[], 22, 'fleetio', false),
  ('TCH-2026-00056', 'Remplacement du capteur de vitesse de roue', 'Remplacement du capteur de vitesse de roue pour assurer un bon fonctionnement du système ABS et de contrôle de traction.', '1', '013', '011', 'curatif', '{}'::text[], 22, 'fleetio', false),
  ('TCH-2026-00057', 'Inspection du filtre à carburant', 'Vérification du filtre à carburant pour s''assurer qu''il est propre et qu''il filtre efficacement le carburant.', '4', '044', '002', 'preventif', '{}'::text[], 21, 'fleetio', false),
  ('TCH-2026-00058', 'Remplissage du liquide de frein', 'Remplissage du liquide de frein pour garantir une performance de freinage fiable.', '5', '053', '999', 'preventif', '{}'::text[], 21, 'fleetio', false),
  ('TCH-2026-00059', 'Inspection de la vanne PCV', 'Vérification de la vanne de ventilation du carter pour assurer un bon fonctionnement.', '4', '045', '014', 'preventif', '{}'::text[], 20, 'fleetio', false),
  ('TCH-2026-00060', 'Remplacement de l''ampoule intérieure', 'Remplacement des ampoules à l''intérieur du véhicule pour une meilleure visibilité.', '3', '034', '004', 'curatif', '{}'::text[], 19, 'fleetio', false),
  ('TCH-2026-00061', 'Remplacement des amortisseurs arrière', 'Remplacement des amortisseurs arrière pour améliorer la suspension et le confort de conduite.', '1', '016', '006', 'curatif', '{}'::text[], 19, 'fleetio', false),
  ('TCH-2026-00062', 'Remplacement du filtre d''air de cabine', 'Remplacement du filtre d''air de cabine pour garantir une bonne qualité de l''air à l''intérieur du véhicule.', '0', '002', '044', 'preventif', '{}'::text[], 19, 'fleetio', false),
  ('TCH-2026-00063', 'HVAC (Divers)', 'Réparations et ajustements divers du système de chauffage, ventilation et climatisation.', '0', '001', null, 'curatif', '{}'::text[], 18, 'fleetio', false),
  ('TCH-2026-00064', 'Remplacement de la courroie de distribution du moteur', 'Remplacement de la courroie de distribution pour éviter les défaillances du moteur.', '4', '045', '002', 'curatif', '{}'::text[], 18, 'fleetio', false),
  ('TCH-2026-00065', 'Remplacement du radiateur', 'Remplacement complet du radiateur pour assurer un refroidissement optimal du moteur.', '4', '042', '002', 'curatif', '{}'::text[], 18, 'fleetio', false),
  ('TCH-2026-00066', 'Remplacement du compresseur de climatisation', 'Remplacement du compresseur de climatisation pour assurer un refroidissement adéquat de l''air.', '0', '001', '001', 'curatif', '{}'::text[], 17, 'fleetio', false),
  ('TCH-2026-00067', 'LAVAGE VEHICULE', null, '9', '999', null, null, '{}'::text[], 16, 'fleetio', false),
  ('TCH-2026-00068', 'Remplacement de l''alternateur', 'Remplacement de l''alternateur pour assurer une charge électrique adéquate de la batterie.', '3', '031', '001', 'curatif', '{}'::text[], 16, 'fleetio', false),
  ('TCH-2026-00069', 'Remplacement de l''ensemble du turbocompresseur', 'Remplacement complet du turbocompresseur pour améliorer les performances du moteur.', '4', '043', '004', 'curatif', '{}'::text[], 16, 'fleetio', false),
  ('TCH-2026-00070', 'Remplacement du maître-cylindre de frein', 'Remplacement du maître-cylindre de frein pour garantir une réponse de freinage efficace.', '1', '013', '006', 'curatif', '{}'::text[], 16, 'fleetio', false),
  ('TCH-2026-00071', 'Suspension arrière (Divers)', 'Divers travaux ou vérifications liés à la suspension arrière non spécifiés.', '1', '016', '023', 'curatif', '{}'::text[], 16, 'fleetio', false),
  ('TCH-2026-00072', 'Freins avant et tambours', 'Vérification ou remplacement des freins avant et des tambours associés.', '1', '013', '001', null, '{}'::text[], 15, 'fleetio', false),
  ('TCH-2026-00073', 'Remplacement du module de contrôle ABS', 'Remplacement du module de contrôle ABS pour assurer le bon fonctionnement du système de freinage antiblocage.', '1', '013', '011', 'preventif', '{}'::text[], 15, 'fleetio', false),
  ('TCH-2026-00074', 'Couple de serrage du système de suspension avant', 'Ajustement du couple de serrage des composants du système de suspension avant pour assurer leur fixation correcte.', '1', '016', '001', 'preventif', '{}'::text[], 14, 'fleetio', false),
  ('TCH-2026-00075', 'Diagnostic (Non spécifié)', 'Diagnostic général pour identifier les problèmes non spécifiés du véhicule.', '9', '999', '999', null, '{}'::text[], 14, 'fleetio', false),
  ('TCH-2026-00076', 'FROID ET ACCESSOIRES', null, '0', '001', null, null, '{}'::text[], 14, 'fleetio', false),
  ('TCH-2026-00077', 'Remplacement de la courroie de distribution', 'Remplacement de la courroie de distribution pour éviter les défaillances du moteur.', '4', '045', '008', 'curatif', '{}'::text[], 14, 'fleetio', false),
  ('TCH-2026-00078', 'ACHAT BATTERIE', null, '3', '032', null, null, '{}'::text[], 13, 'fleetio', false),
  ('TCH-2026-00079', 'Airbag - Assemblage, Côté conducteur, Avant', 'Remplacement ou réparation de l''assemblage de l''airbag côté conducteur à l''avant du véhicule.', '0', '002', '057', null, '{}'::text[], 13, 'fleetio', false),
  ('TCH-2026-00080', 'ampoule veilleuse', null, '3', '034', null, null, '{}'::text[], 13, 'fleetio', false),
  ('TCH-2026-00081', 'BALLON AIR', null, '1', '013', null, null, '{}'::text[], 13, 'fleetio', false),
  ('TCH-2026-00082', 'Inspection de l''ensemble des pneus', 'Vérification de l''état des pneus pour détecter tout problème ou usure.', '1', '017', null, 'preventif', '{}'::text[], 13, 'fleetio', false),
  ('TCH-2026-00083', '12V 10W BULB', null, '3', '034', null, null, '{}'::text[], 12, 'fleetio', false),
  ('TCH-2026-00084', 'Fournitures pour atelier', 'Fournitures diverses nécessaires pour l''entretien et la réparation des véhicules.', '5', '053', '011', null, '{}'::text[], 12, 'fleetio', false),
  ('TCH-2026-00085', 'Remplacement des amortisseurs ou des jambes de force', 'Remplacement des amortisseurs ou des jambes de force pour assurer une conduite confortable et sécurisée.', '1', '016', null, 'curatif', '{}'::text[], 12, 'fleetio', false),
  ('TCH-2026-00086', 'Remplacement des injecteurs de carburant', 'Remplacement des injecteurs pour assurer une combustion correcte du carburant.', '4', '044', '014', 'curatif', '{}'::text[], 12, 'fleetio', false),
  ('TCH-2026-00087', 'Remplacement du rétroviseur extérieur', 'Remplacement du rétroviseur extérieur pour une meilleure visibilité et sécurité.', '0', '002', '010', 'curatif', '{}'::text[], 12, 'fleetio', false),
  ('TCH-2026-00088', 'Remplissage du liquide de transmission', 'Remplissage du liquide de transmission pour assurer un fonctionnement optimal de la transmission.', '5', '053', '999', 'preventif', '{}'::text[], 12, 'fleetio', false),
  ('TCH-2026-00089', 'Inspecter le niveau de liquide du système de refroidissement', 'Vérification du niveau de liquide dans le système de refroidissement pour éviter la surchauffe du moteur.', '4', '042', null, null, '{}'::text[], 11, 'fleetio', false),
  ('TCH-2026-00090', 'Inspection Multi-Points du Véhicule', 'Vérification complète du véhicule à plusieurs points pour assurer son bon état général.', '9', '999', '999', 'preventif', '{}'::text[], 11, 'fleetio', false),
  ('TCH-2026-00091', 'Lubricate Grease Points', null, '5', '053', null, null, '{}'::text[], 11, 'fleetio', false),
  ('TCH-2026-00092', 'Ajouter un conditionneur de liquide au système de refroidissement', 'Ajoutez un conditionneur pour améliorer les performances et la durée de vie du liquide de refroidissement.', '5', '053', '999', null, '{}'::text[], 10, 'fleetio', false),
  ('TCH-2026-00093', 'Evacuation et recharge du système de climatisation', 'Evacuation et recharge du réfrigérant pour assurer le bon fonctionnement du système de climatisation.', '0', '001', '001', null, '{}'::text[], 10, 'fleetio', false),
  ('TCH-2026-00094', 'Inspection de la barre de direction', 'Vérification de la barre de direction pour détecter tout signe d''usure ou de dommage.', '1', '015', '004', 'preventif', '{}'::text[], 10, 'fleetio', false),
  ('TCH-2026-00095', 'Peinture de la carrosserie', 'Application de peinture sur la carrosserie pour réparer les éraflures ou les dommages.', '0', '002', null, 'curatif', '{}'::text[], 10, 'fleetio', false),
  ('TCH-2026-00096', 'Remplissage du liquide de direction assistée', 'Remplissage du liquide de direction assistée pour assurer une direction fluide.', '5', '053', '999', 'preventif', '{}'::text[], 10, 'fleetio', false),
  ('TCH-2026-00097', 'feu de gabarie', null, '3', '034', null, null, '{}'::text[], 9, 'fleetio', false),
  ('TCH-2026-00098', 'Inspection de la courroie de distribution du moteur', 'Vérification de la courroie de distribution pour détecter l''usure ou les dommages.', '4', '045', '002', 'preventif', '{}'::text[], 9, 'fleetio', false),
  ('TCH-2026-00099', 'Inspection des tuyaux du système de refroidissement', 'Vérification des tuyaux du système de refroidissement pour détecter les fuites, les fissures ou les signes d''usure.', '4', '042', null, 'preventif', '{}'::text[], 9, 'fleetio', false),
  ('TCH-2026-00100', 'JEU DE PLAQUETTE', null, '1', '013', null, null, '{}'::text[], 9, 'fleetio', false),
  ('TCH-2026-00101', 'Remplacement du moteur de démarrage', 'Remplacement du moteur de démarrage pour garantir un démarrage fiable du véhicule.', '3', '032', '002', 'curatif', '{}'::text[], 9, 'fleetio', false),
  ('TCH-2026-00102', 'Vérification du niveau de liquide du maître-cylindre d''embrayage', 'Vérification du niveau de liquide du maître-cylindre d''embrayage pour s''assurer qu''il est adéquat.', '5', '053', '999', 'preventif', '{}'::text[], 9, 'fleetio', false),
  ('TCH-2026-00103', 'vidange huile moteur', null, '4', '045', null, 'preventif', '{}'::text[], 9, 'fleetio', false),
  ('TCH-2026-00104', 'Inspection du soufflet du joint homocinétique', 'Vérification du soufflet du joint homocinétique pour éviter des fuites de graisse ou des dommages.', '2', '021', '001', 'preventif', '{}'::text[], 8, 'fleetio', false),
  ('TCH-2026-00105', 'Remplacement des balais d''essuie-glace', 'Remplacement des balais d''essuie-glace usés pour assurer une visibilité optimale par temps de pluie.', '0', '002', '035', 'curatif', '{}'::text[], 8, 'fleetio', false),
  ('TCH-2026-00106', 'Remplacement du tuyau d''échappement', 'Remplacement du tuyau d''échappement pour assurer un bon flux des gaz d''échappement.', '4', '043', '003', 'curatif', '{}'::text[], 8, 'fleetio', false),
  ('TCH-2026-00107', 'Airbag - Assemblage, Porte du conducteur', 'Remplacement ou réparation de l''assemblage de l''airbag dans la porte du conducteur.', '0', '002', '057', null, '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00108', 'appareil frein à main', null, '1', '013', null, null, '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00109', 'batterie75AH', null, '3', '032', null, null, '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00110', 'COLE SILICONE', null, '5', '053', null, null, '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00111', 'Inspection de l''arbre de transmission', 'Vérification de l''arbre de transmission pour détecter l''usure, les fissures ou les déséquilibres.', '2', '024', null, 'preventif', '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00112', 'Inspection des amortisseurs arrière', 'Vérification de l''état des amortisseurs arrière pour détecter tout signe de fuite ou usure.', '1', '016', '006', 'preventif', '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00113', 'Inspection des conduites du refroidisseur d''huile de transmission', 'Vérification des conduites du refroidisseur d''huile de transmission pour détecter toute fuite ou usure.', '2', null, null, 'preventif', '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00114', 'JEU DE SEGMENT', null, '4', '045', null, null, '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00115', 'POUMON FREIN', null, '1', '013', null, null, '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00116', 'prise courant', null, '3', '034', null, null, '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00117', 'Vidange, remplissage et purge du système hydraulique de freinage', 'Vidange, remplissage et purge du liquide de freinage pour assurer un freinage optimal.', '1', '013', '007', 'preventif', '{}'::text[], 7, 'fleetio', false),
  ('TCH-2026-00118', 'ACHATS PNEU 385', null, '1', '017', null, null, '{}'::text[], 6, 'fleetio', false),
  ('TCH-2026-00119', 'APPAREIL DESSICATEUR AXOR', null, '1', '013', null, null, '{}'::text[], 6, 'fleetio', false),
  ('TCH-2026-00120', 'Bouchon de remplissage du réservoir de carburant', 'Vérification et remplacement du bouchon de remplissage pour assurer une bonne étanchéité du réservoir de carburant.', '4', '044', '001', 'preventif', '{}'::text[], 6, 'fleetio', false),
  ('TCH-2026-00121', 'Inspection des niveaux de fluide du véhicule', 'Vérification des niveaux de fluide dans le véhicule pour s''assurer qu''ils sont adéquats.', '9', '999', '999', 'preventif', '{}'::text[], 6, 'fleetio', false),
  ('TCH-2026-00122', 'Remplacement de la pompe à huile', 'Remplacement de la pompe à huile pour assurer une lubrification adéquate du moteur.', '4', '045', '009', 'preventif', '{}'::text[], 6, 'fleetio', false),
  ('TCH-2026-00123', 'Remplacement des bougies d''allumage', 'Remplacement des bougies d''allumage pour garantir un démarrage facile et une performance optimale du moteur.', '3', '033', '003', 'curatif', '{}'::text[], 6, 'fleetio', false),
  ('TCH-2026-00124', 'REMPLACEMENT ETRIER ARRIERE', null, '1', '013', null, 'curatif', '{}'::text[], 6, 'fleetio', false),
  ('TCH-2026-00125', 'ACHAT PNEU 315', null, '1', '017', null, null, '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00126', 'Airbag - Porte de cabine', 'Remplacement ou réparation de l''airbag dans la porte de cabine.', '0', '002', '057', null, '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00127', 'COMMANDE BOUDIN', null, '1', '013', null, null, '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00128', 'Compresseur Golden Shop', 'Partie du moteur d''un frigo', '0', '001', null, null, '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00129', 'Couple de serrage de la bride de l''arbre de transmission', 'Vérification et réglage du couple de serrage des boulons de la bride de l''arbre de transmission.', '2', '022', '003', 'preventif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00130', 'Inspection de l''élément du filtre à air du moteur', 'Vérification de l''élément du filtre à air pour s''assurer qu''il est propre et qu''il filtre efficacement l''air entrant dans le moteur.', '4', '041', '001', 'preventif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00131', 'Inspection des freins', 'Vérification des composants de freinage pour s''assurer qu''ils sont en bon état et fonctionnent efficacement.', '1', '013', null, 'preventif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00132', 'Inspection du condenseur de climatisation', 'Vérification du condenseur de climatisation pour s''assurer qu''il est propre et fonctionne correctement pour un refroidissement efficace.', '0', '001', '001', 'preventif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00133', 'Inspection du système de climatisation', 'Vérification du système de climatisation pour détecter les problèmes éventuels.', '0', '001', '001', 'preventif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00134', 'Moteur Frigo', null, '4', '045', null, null, '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00135', 'PLAQUETTE FREIN', null, '1', '013', null, null, '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00136', 'RELAIS STOP', null, '3', '034', null, null, '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00137', 'Remise en état Sinistre', 'Réparation véhicule suite accident/ Incident', '0', '002', null, null, '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00138', 'Remplacement de l''assemblage du ventilateur de radiateur', 'Remplacement du ventilateur de radiateur pour garantir un refroidissement efficace du moteur.', '4', '042', '003', 'curatif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00139', 'Remplacement de la culasse', 'Remplacement de la culasse pour résoudre les problémes de fuite ou de défaillance du moteur.', '4', '045', '007', 'curatif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00140', 'Remplacement de la poulie tendeur de la courroie de distribution', 'Remplacement de la poulie tendeur pour assurer une tension correcte de la courroie de distribution.', '4', '045', '008', 'curatif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00141', 'Remplacement des amortisseurs avant', 'Remplacement des amortisseurs avant usés pour améliorer la stabilité et le confort de conduite.', '1', '016', '003', 'curatif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00142', 'SEGMENT COMPRESSEUR', null, '0', '001', null, null, '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00143', 'Test du système de climatisation', 'Vérification du système de climatisation pour s''assurer qu''il fonctionne efficacement.', '0', '001', '001', 'preventif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00144', 'VANNE AIRE', null, '1', '013', null, null, '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00145', 'verification circuit froid', null, '0', '001', null, 'preventif', '{}'::text[], 5, 'fleetio', false),
  ('TCH-2026-00146', 'BOUDIN LAC PM', null, '1', '013', null, null, '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00147', 'Bouteille gaz', null, '5', '053', null, null, '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00148', 'crochet teton', null, '9', '999', null, null, '{}'::text[], 4, 'fleetio', true),
  ('TCH-2026-00149', 'Equilibrage des pneus', 'Equilibrage des pneus pour éviter les vibrations et assurer une conduite en douceur.', '1', '017', '001', 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00150', 'Inspection de la liaison de direction', 'Vérification de la liaison de direction pour détecter les usures ou les dommages.', '1', '015', '004', 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00151', 'Inspection des amortisseurs avant', 'Vérification de l''état des amortisseurs avant pour détecter toute fuite ou défaillance.', '1', '016', '003', 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00152', 'Inspection des amortisseurs ou des jambes de force', 'Vérification des amortisseurs ou des jambes de force pour assurer leur bon état.', '1', '016', null, 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00153', 'Inspection des fuites du système de refroidissement', 'Vérification du système de refroidissement pour détecter toute fuite de liquide qui pourrait provoquer une surchauffe.', '4', '042', null, 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00154', 'Inspection du bouchon de remplissage du réservoir de carburant', 'Vérification du bouchon de remplissage pour s''assurer qu''il est en bon état et qu''il scelle correctement le réservoir.', '4', '044', '001', 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00155', 'Inspection du jeu de soupape', 'Vérification du jeu de soupape pour s''assurer qu''il est dans les spécifications correctes.', '4', '043', '005', 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00156', 'Inspection du niveau de liquide de réduction des émissions diesel (AdBlue)', 'Vérification du niveau de liquide AdBlue pour garantir que les émissions sont correctement réduites.', '4', '043', '007', 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00157', 'Inspection du niveau de liquide du système de freinage hydraulique', 'Vérification du niveau de liquide de freinage hydraulique pour garantir une performance de freinage adéquate.', '1', '013', '007', 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00158', 'Inspection du système de ceinture de sécurité', 'Vérification du système de ceinture de sécurité pour garantir son bon fonctionnement et sécurité.', '0', '002', '011', 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00159', 'KLAXON', null, '3', '034', null, null, '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00160', 'Lubrification du système de suspension', 'Application de lubrifiant dans le système de suspension pour assurer son bon fonctionnement.', '1', '016', null, 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00161', 'Remplacement des garnitures de frein', 'Remplacement des garnitures de frein pour assurer une performance de freinage efficace.', '1', '013', '017', 'curatif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00162', 'Remplacement du pare-brise', 'Remplacement complet du pare-brise pour garantir la sécurité et la visibilité.', '0', '002', '024', 'curatif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00163', 'Remplacement du thermostat de liquide de refroidissement', 'Remplacement du thermostat pour maintenir la température du moteur dans la plage optimale.', '4', '042', '006', 'curatif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00164', 'Remplissage du liquide de refroidissement', 'Remplissage du liquide de refroidissement pour maintenir une température moteur optimale.', '4', '042', null, 'preventif', '{}'::text[], 4, 'fleetio', false),
  ('TCH-2026-00165', 'Alignement des roues', 'Réglage de l''alignement des roues pour assurer une conduite stable et éviter l''usure inégale des pneus.', '1', '018', '003', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00166', 'APPAREIL DISTRIBUTEUR', null, '1', '013', null, null, '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00167', 'APPAREIL ROBOT A VITESSE', null, '2', '026', null, null, '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00168', 'CARTOUCHE GASOIL', null, '4', '044', null, null, '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00169', 'CONFECTIONNEUSE ECROUS', null, '9', '999', null, null, '{}'::text[], 3, 'fleetio', true),
  ('TCH-2026-00170', 'Couple de serrage des boulons de montage de l''ensemble du pont avant', 'Vérification et ajustement du couple de serrage des boulons qui fixent l''essieu avant.', '2', '021', '002', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00171', 'Couple des boulons de fixation de l''ensemble de l''essieu de traction', 'Vérification et réglage du couple de serrage des boulons de l''essieu de traction.', '2', null, null, 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00172', 'Couple des boulons de montage de l''ensemble essieu arrière', 'Vérification et ajustement du couple des boulons de montage pour assurer une fixation sécurisée.', '2', '022', '007', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00173', 'DISQUE EMBRAYAGE MERCEDES AXOR', null, '1', '013', null, null, '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00174', 'Essai routier du véhicule', 'Test de conduite du véhicule pour vérifier son bon fonctionnement.', '9', '999', '999', null, '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00175', 'Graisse', null, '5', '053', null, null, '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00176', 'Inspection de fuite de transmission automatique', 'Vérification du système de transmission automatique pour détecter toute fuite de liquide.', '2', '027', null, 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00177', 'Inspection de l''assemblage de la boîte de direction', 'Vérification de l''assemblage de la boîte de direction pour détecter l''usure ou les dommages.', '1', '015', '013', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00178', 'Inspection de l''ensemble roue et pneu', 'Vérification de l''ensemble roue et pneu pour détecter tout problème ou usure.', '1', '017', null, 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00179', 'Inspection du bouchon de radiateur', 'Vérification du bouchon de radiateur pour s''assurer qu''il maintient la pression correcte.', '4', '042', '008', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00180', 'Inspection du câble de batterie, Batterie à la masse', 'Vérification du câble de batterie reliant la batterie à la masse pour assurer une bonne connexion.', '3', '032', '001', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00181', 'Inspection du frein à main', 'Vérification du système de frein à main pour s''assurer qu''il fonctionne correctement.', '1', '013', '003', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00182', 'Inspection du joint universel de l''arbre de transmission', 'Vérification de l''état du joint universel sur l''arbre de transmission pour éviter les bruits ou vibrations.', '2', '024', '002', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00183', 'Inspection du moniteur de durée de vie de l''huile', 'Vérification du moniteur pour déterminer le moment approprié pour changer l''huile moteur.', '0', '003', '001', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00184', 'Inspection du réservoir de carburant', 'Vérification du réservoir de carburant pour détecter les signes de corrosion, de fuites ou de dommages.', '4', '044', '001', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00185', 'Inspection du système de carburant', 'Vérification du système de carburant pour s''assurer de son bon fonctionnement et identifier les problèmes potentiels.', '4', '044', null, 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00186', 'Inspection du système de direction', 'Vérification du système de direction pour détecter tout problème ou usure.', '1', '015', null, 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00187', 'PISTON COMPRESSEUR', null, '0', '001', null, null, '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00188', 'POUMON ARRIERE', null, '1', '013', null, null, '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00189', 'raccord', null, '9', '999', null, null, '{}'::text[], 3, 'fleetio', true),
  ('TCH-2026-00190', 'Remplacement de l''arbre d''essieu', 'Remplacement de l''arbre d''essieu pour résoudre les problèmes de transmission de puissance.', '2', null, null, 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00191', 'Remplacement de l''embrayage du ventilateur de radiateur', 'Remplacement de l''embrayage du ventilateur de radiateur pour assurer un bon fonctionnement.', '4', '042', '003', 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00192', 'Remplacement de la barre de direction', 'Remplacement de la barre de direction pour maintenir une direction précise et une conduite sûre.', '1', '015', '004', 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00193', 'Remplacement de la pompe de direction assistée', 'Remplacement de la pompe pour maintenir une direction assistée efficace.', '1', '015', '005', 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00194', 'Remplacement de la vanne EGR', 'Remplacement de la vanne de recirculation des gaz d''échappement pour améliorer les emissions.', '4', '043', '001', 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00195', 'Remplacement du joint à rotule de suspension avant', 'Remplacement du joint à rotule de la suspension avant pour assurer une conduite en douceur et sans jeu.', '1', '016', '001', 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00196', 'Remplacement du tambour de frein', 'Remplacement du tambour de frein pour garantir une performance de freinage optimale.', '1', '013', '017', 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00197', 'Remplacement du tuyau du radiateur', 'Remplacement du tuyau du radiateur pour éviter les fuites et les surchauffes.', '4', '042', '003', 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00198', 'Remplacement Phare', null, '3', '034', '001', 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00199', 'réparation contacteur', null, '3', '033', null, 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00200', 'Système de direction (Divers)', 'Divers travaux ou vérifications liés au système de direction non spécifiés.', '1', '015', null, 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00201', 'Système de refroidissement du moteur (Divers)', 'Réparations et ajustements divers du système de refroidissement du moteur.', '4', '042', null, 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00202', 'Test de la batterie', 'Vérification de l''état de la batterie pour s''assurer qu''elle fonctionne correctement.', '3', '032', '001', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00203', 'Transmission manuelle (Divers)', 'Divers travaux ou vérifications liés à la transmission manuelle non spécifiés.', '2', '026', null, 'curatif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00204', 'Vidange et remplissage du système hydraulique d''embrayage', 'Vidange du liquide et remplissage du système hydraulique d''embrayage pour garantir son bon fonctionnement.', '2', '023', '002', 'preventif', '{}'::text[], 3, 'fleetio', false),
  ('TCH-2026-00205', 'Acide batterie', null, '3', '032', null, null, '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00206', 'Airbag - Assemblage, Côté passager, avant', 'Remplacement ou réparation de l''assemblage de l''airbag côté passager à l''avant du véhicule.', '0', '002', '057', null, '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00207', 'appareil electrovanne', null, '1', '013', null, null, '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00208', 'cole crezi', null, '5', '053', null, null, '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00209', 'Couple du système de suspension pneumatique', 'Vérification et réglage du couple de serrage des composants du système de suspension pneumatique.', '1', '016', '008', null, '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00210', 'Démarrage du véhicule par câbles', 'Démarrage du véhicule à l''aide de câbles pour résoudre les problèmes de batterie.', '3', '032', null, null, '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00211', 'Entretien Frigo Golden Shop', null, '0', '001', null, 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00212', 'Fréon Golden Shop (R 134 A, R 22, R 410 ou R 141)', null, '9', '999', null, null, '{}'::text[], 2, 'fleetio', true),
  ('TCH-2026-00213', 'Inspection de l''alignement des phares', 'Vérification et ajustement de l''alignement des phares pour une visibilité optimale lors de la conduite de nuit.', '3', '034', '001', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00214', 'Inspection de l''alignement des roues', 'Vérification de l''alignement des roues pour assurer une conduite stable et un usure uniforme des pneus.', '1', '018', '003', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00215', 'Inspection de l''étrier de frein à disque', 'Vérification de l''étrier de frein à disque pour détecter l''usure ou les dommages pouvant affecter les performances de freinage.', '1', '013', '017', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00216', 'Inspection de l''étrier de frein à disque arrière', 'Vérification de l''étrier de frein à disque', '1', '013', '002', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00217', 'Inspection de la conduite de frein', 'Vérification des conduites de frein pour détecter les fuites ou les dommages.', '1', '013', '017', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00218', 'Inspection du câble de batterie', 'Vérification de l''état des câbles de batterie pour s''assurer qu''ils sont bien fixés et exempts de corrosion.', '3', '032', '001', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00219', 'Inspection du manomètre de restriction du filtre à air', 'Vérification du manomètre qui mesure la restriction du filtre à air pour assurer une bonne circulation d''air.', '0', '003', '001', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00220', 'Inspection du niveau de liquide de direction assistée', 'Vérification du niveau de liquide de direction assistée pour garantir une direction fluide et précise.', '5', '053', '999', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00221', 'Inspection du niveau de liquide de transmission', 'Vérification du niveau de liquide de transmission pour s''assurer qu''il est adéquat.', '5', '053', '999', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00222', 'Inspection du scellant du kit de réparation de pneus', 'Vérification du scellant du kit de réparation de pneus pour s''assurer qu''il est en bon état.', '5', '053', '999', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00223', 'Inspection du système d''échappement', 'Vérification de l''état et du fonctionnement du système d''échappement pour détecter les fuites ou les dommages.', '4', '043', null, 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00224', 'Inspection du système de suspension', 'Vérification complète du système de suspension pour détecter tout problème ou usure.', '1', '016', null, 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00225', 'Lampe, Filtre, Capillaire Golden Shop', 'Changement ou remplacement de lampe, filtre ou capillaire, frigo', '1', '013', null, 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00226', 'Nettoyage du boîtier du filtre à air du moteur', 'Nettoyage du boîtier du filtre à air pour garantir une bonne circulation d''air dans le moteur.', '4', '041', '001', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00227', 'PAQUETS LAM', null, '9', '999', null, null, '{}'::text[], 2, 'fleetio', true),
  ('TCH-2026-00228', 'POUMON AIR', null, '1', '013', null, null, '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00229', 'Réglage du jeu des soupapes', 'Réglage du jeu des soupapes pour assurer une performance optimale du moteur.', '4', '043', '005', null, '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00230', 'Remplacement de l''ensemble de transmission automatique', 'Remplacement complet de l''assemblage de transmission automatique pour résoudre les problèmes de transmission.', '2', '027', '037', 'curatif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00231', 'Remplacement de l''ensemble moteur', 'Remplacement complet du moteur pour résoudre des problèmes majeurs.', '4', '045', null, 'curatif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00232', 'Remplacement de la pompe à vide de frein', 'Remplacement de la pompe qui aide à créer la dépression nécessaire au fonctionnement du freinage.', '1', '013', '008', 'curatif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00233', 'Remplacement de la vanne d''expansion de climatisation', 'Remplacement de la vanne d''expansion pour maintenir un système de climatisation efficace.', '0', '001', '001', 'curatif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00234', 'Remplacement du boîtier de thermostat de liquide de refroidissement', 'Remplacement du boîtier du thermostat pour assurer un bon contrôle de la température du moteur.', '4', '042', '006', 'curatif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00235', 'Remplacement du jeu de fils de bougies', 'Remplacement du jeu de fils de bougies pour assurer un allumage efficace et une performance du moteur optimale.', '3', '033', '003', 'curatif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00236', 'Remplacement du joint de rotule de suspension', 'Remplacement des joints de rotule pour maintenir une bonne maniabilité.', '1', '016', null, 'curatif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00237', 'Remplacement du joint de vilebrequin avant', 'Remplacement du joint de vilebrequin avant pour éviter les fuites d''huile.', '4', '045', '003', 'curatif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00238', 'Remplacement du pare-chocs', 'Remplacement du pare-chocs avant ou arrière pour la protection et l''esthétique du véhicule.', '1', '014', '002', 'curatif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00239', 'Remplacement du régulateur/moteur de fenêtre', 'Remplacement du régulateur ou moteur de fenêtre pour garantir un fonctionnement correct de la fenêtre.', '0', '002', '018', 'curatif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00240', 'Remplacement Huile de différentiel', null, '2', '022', null, 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00241', 'Ventilo, Condenseur Golden Shop', 'Ventillateur et condenseur Frofo', '9', '999', null, null, '{}'::text[], 2, 'fleetio', true),
  ('TCH-2026-00242', 'Vidange du séparateur d''eau du filtre à carburant', 'Vidange du séparateur d''eau intégré au filtre à carburant pour éviter la contamination par l''eau.', '4', '044', '002', 'preventif', '{}'::text[], 2, 'fleetio', false),
  ('TCH-2026-00243', 'Airbag - Assemblage, Porte passager', 'Remplacement ou réparation de l''assemblage de l''airbag dans la porte passager.', '0', '002', '057', null, '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00244', 'appareil purchage', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00245', 'AWD Filter Replacement', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00246', 'bicones', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00247', 'Brake Hydraulic Oil Replacement', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00248', 'CARTOUCHE VERIN', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00249', 'Circle Drive Oil Replacement', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00250', 'Couple des écrous de roue', 'Vérification et ajustement du couple des écrous de roue pour assurer une fixation correcte.', '1', '018', '003', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00251', 'Couple des fixations de carrosserie', 'Vérification et réglage du couple de serrage des fixations de la carrosserie.', '1', '014', '001', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00252', 'CROIE HELICE', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00253', 'Déchets de l''état/province', 'Gestion des déchets produits par les opérations de maintenance dans la région ou province.', '9', '999', '999', null, '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00254', 'Désinfection et désincestisation', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00255', 'GLACIOLE EAUX', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00256', 'goujon', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00257', 'Hydraulic Oil Filter Replacement', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00258', 'Inspection de l''assemblage de crémaillère et pignon', 'Vérification de l''assemblage de crémaillère et pignon pour s''assurer qu''il n''est pas usé ou endommagé.', '1', '015', '013', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00259', 'Inspection de l''ensemble du pont avant', 'Inspection visuelle et fonctionnelle de l''essieu avant pour détecter toute usure ou dommage.', '2', '021', '002', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00260', 'Inspection de l''ensemble essieu arrière', 'Vérification de l''état de l''ensemble essieu arrière pour détecter les signes d''usure ou de dommage.', '2', '022', '007', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00261', 'Inspection de l''ensemble essieu moteur', 'Vérification de l''assemblage de l''essieu moteur pour détecter les usures ou les dommages.', '2', null, null, 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00262', 'Inspection de l''étrier de frein à disque avant', 'Vérification de l''étrier de frein avant pour assurer un freinage efficace.', '1', '013', '001', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00263', 'Inspection de la buse du lave-glace des phares', 'Vérification de la buse du lave-glace pour s''assurer qu''elle pulvérise le liquide correctement sur les phares.', '0', '002', '065', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00264', 'Inspection de la conduite de carburant', 'Vérification des conduites de carburant pour détecter les fuites, les fissures ou les dommages.', '4', '044', '001', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00265', 'Inspection de la conduite de vide', 'Vérification de la conduite de vide pour détecter tout signe d''usure ou de dommage.', '4', '041', '002', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00266', 'Inspection de la pédale d''accélérateur', 'Vérification de la pédale d''accélérateur pour s''assurer qu''elle fonctionne correctement et sans obstruction.', '4', '044', '007', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00267', 'Inspection des balais d''essuie-glace', 'Vérification des balais d''essuie-glace pour détecter toute usure ou défaillance.', '0', '002', '035', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00268', 'Inspection des conduites du système de contrôle des émissions d''évaporation du carburant', 'Vérification des conduites du système d''émission pour détecter les fuites ou les obstructions.', '4', '044', '016', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00269', 'Inspection des freins à tambour', 'Vérification des freins à tambour pour s''assurer qu''ils sont en bon état et fonctionnent correctement.', '1', '013', '017', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00270', 'Inspection des freins à tambour arrière', 'Vérification des freins à tambour arrière pour détecter l''usure ou les problèmes de fonctionnement.', '1', '013', '002', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00271', 'Inspection des garnitures de frein', 'Vérification de l''épaisseur et de l''état des garnitures de frein pour assurer un freinage efficace et sécuritaire.', '1', '013', '017', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00272', 'Inspection des garnitures de frein arrière', 'Vérification des garnitures de frein arrière pour assurer une performance de freinage optimale.', '1', '013', '002', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00273', 'Inspection des verrous, des loquets et des charnières de carrosserie', 'Vérification des verrous, loquets et charnières pour assurer leur bon fonctionnement.', '1', '014', '004', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00274', 'Inspection du câble de batterie, Batterie (série)', 'Vérification des câbles de batterie en série pour s''assurer de la connexion correcte.', '3', '032', '001', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00275', 'Inspection du câble de batterie, de la batterie au démarreur', 'Vérification du câble de batterie reliant la batterie au démarreur pour assurer un démarrage fiable.', '3', '032', '001', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00276', 'Inspection du corps de papillon', 'Vérification du corps de papillon pour assurer un contrôle précis de l''accélérateur.', '4', '041', '006', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00277', 'Inspection du filtre à air de l''habitacle', 'Vérification du filtre à air de l''habitacle pour s''assurer qu''il est propre et qu''il filtre efficacement l''air entrant dans l''habitacle.', '0', '002', '044', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00278', 'Inspection du joint à rotule de la suspension', 'Vérification du joint à rotule de la suspension pour détecter tout signe d''usure ou de dommage.', '1', '016', null, 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00279', 'Inspection du joint à rotule de la suspension pneumatique', 'Vérification du joint à rotule de la suspension pneumatique pour s''assurer qu''il n''est pas usé ou endommagé.', '1', '016', '008', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00280', 'Inspection du joint d''étanchéité', 'Vérification du joint d''étanchéité pour détecter tout signe d''usure ou de dommage.', '0', '002', '026', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00281', 'Inspection du niveau de liquide de transmission automatique', 'Vérification du niveau du liquide de transmission automatique pour assurer un fonctionnement optimal.', '2', '027', null, 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00282', 'Inspection du solénoïde de verrouillage de frein de transmission automatique', 'Vérification du solénoïde qui contrôle le verrouillage du frein de transmission pour un fonctionnement correct.', '2', '027', '033', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00283', 'Inspection du système d''airbags', 'Vérification du système d''airbags pour assurer son bon fonctionnement en cas d''accident.', '0', '002', '057', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00284', 'Inspection du système de suspension arrière', 'Vérification complète du système de suspension arrière pour détecter tout problème ou usure.', '1', '016', '023', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00285', 'Inspection du système de suspension pneumatique', 'Vérification complète du système de suspension pneumatique pour détecter des fuites ou défaillances.', '1', '016', '008', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00286', 'JEU DE GARNITURE', null, '1', '013', null, null, '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00287', 'JEUX ARRET MERCESDES AXOR', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00288', 'Location de véhicule', 'Location véhicule de remplacement', '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00289', 'Lubrification de la barre de direction', 'Application de lubrifiant à la barre de direction pour assurer un fonctionnement fluide.', '1', '015', '004', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00290', 'Lubrification de la liaison de direction', 'Application de lubrifiant à la liaison de direction pour assurer un fonctionnement fluide.', '1', '015', '004', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00291', 'Lubrification des charnières de porte', 'Application de lubrifiant sur les charnières de porte pour assurer une ouverture et fermeture en douceur.', '0', '002', '018', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00292', 'Nettoyage de l''écran de débris du tuyau d''admission d''air', 'Nettoyage de l''écran de débris dans le tuyau d''admission d''air pour éviter les obstructions.', '4', '041', '001', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00293', 'Nettoyage de la vanne EGR', 'Nettoyage de la vanne EGR pour améliorer l''efficacité du moteur et réduire les émissions.', '4', '043', '006', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00294', 'PNEU 215', null, '1', '017', null, null, '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00295', 'POCHETTE DE GAIN', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00296', 'Re-couple des écrous du moyeu de roue', 'Vérification et ajustement du couple des écrous du moyeu pour assurer une fixation sécurisée.', '1', '018', '003', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00297', 'Régénération du filtre à particules diesel', 'Processus de nettoyage du filtre à particules diesel pour maintenir son efficacité.', '4', '043', '001', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00298', 'Remplacement de l''ensemble de transmission manuelle', 'Remplacement complet de l''assemblage de transmission manuelle pour résoudre les problèmes de transmission.', '2', '026', '012', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00299', 'Remplacement de l''ensemble récepteur-deshydrateur de climatisation', 'Remplacement du récepteur-deshydrateur pour maintenir l''efficacité du système de climatisation.', '0', '001', '001', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00300', 'Remplacement de l''étrier de frein à disque', 'Remplacement de l''étrier de frein à disque pour améliorer la performance de freinage.', '1', '013', '017', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00301', 'Remplacement de l''extrémité de la barre de direction', 'Remplacement de l''extrémité de la barre de direction pour assurer une direction précise et sécurisée.', '1', '015', '004', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00302', 'Remplacement de la barre stabilisatrice avant', 'Remplacement de la barre stabilisatrice avant pour garantir une conduite stable et sécurisée.', '1', '016', '004', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00303', 'Remplacement de la batterie de la télécommande d''entrée sans clé', 'Remplacement de la batterie dans la télécommande d''entrée sans clé pour assurer son bon fonctionnement.', '0', '002', '018', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00304', 'Remplacement de la conduite de frein', 'Remplacement des conduites de frein pour éviter les fuites et garantir une performance de freinage fiable.', '1', '013', '007', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00305', 'Remplacement de la vanne PCV', 'Remplacement de la vanne de ventilation du carter pour améliorer la performance du moteur.', '4', '045', '014', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00306', 'Remplacement du Câble de Frein à Main', null, '1', '013', '003', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00307', 'Remplacement du capteur TPMS', 'Remplacement du capteur de surveillance de la pression des pneus pour assurer la sécurité des pneus.', '1', '017', '009', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00308', 'Remplacement du col de remplissage du réservoir de carburant', 'Remplacement du col de remplissage endommagé pour éviter les fuites de carburant.', '4', '044', '001', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00309', 'Remplacement du condenseur de climatisation', 'Remplacement du condenseur pour garantir une performance efficace du système de climatisation.', '0', '001', '001', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00310', 'Remplacement du convertisseur catalytique', 'Remplacement du convertisseur catalytique pour réduire les émissions nocives du moteur.', '4', '043', '001', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00311', 'Remplacement du différentiel', 'Remplacement du différentiel pour résoudre les problèmes de transmission de puissance et d''engrenage.', '2', '022', '003', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00312', 'Remplacement du filtre de la pompe du liquide d''échappement diesel', 'Remplacement du filtre de la pompe pour assurer le bon fonctionnement du système de traitement des émissions.', '4', '043', '007', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00313', 'Remplacement du filtre de transmission', 'Remplacement du filtre de transmission pour assurer un fonctionnement optimal.', '2', null, null, 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00314', 'Remplacement du filtre de transmission automatique', 'Remplacement du filtre de transmission automatique pour assurer un bon fonctionnement et une longue durée de vie.', '2', '027', '036', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00315', 'Remplacement du filtre du séparateur d''huile du carter', 'Remplacement du filtre qui sépare l''huile des autres contaminants dans le carter moteur.', '4', '045', '014', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00316', 'Remplacement du joint d''étanchéité du roulement de roue', 'Remplacement du joint d''étanchéité pour éviter les fuites de lubrifiant et maintenir le roulement en bon état.', '1', '018', '005', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00317', 'Remplacement du joint du collecteur d''admission', 'Remplacement du joint du collecteur d''admission pour éviter les fuites d''air.', '4', '041', '002', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00318', 'Remplacement du lien de barre stabilisatrice', 'Remplacement des liens de la barre stabilisatrice pour améliorer la stabilité du véhicule.', '1', '016', null, 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00319', 'Remplacement du moyeu de roue', 'Remplacement du moyeu de roue pour garantir une performance de conduite optimale.', '1', '018', '005', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00320', 'Remplacement du noyau évaporateur de climatisation', 'Remplacement du noyau évaporateur pour garantir un bon refroidissement de l''air dans le véhicule.', '0', '001', '001', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00321', 'Remplacement du pare-chocs arrière', 'Remplacement du pare-chocs arrière pour réparer les dommages ou améliorer l''apparence.', '1', '014', '002', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00322', 'Remplacement du pare-chocs avant', 'Remplacement du pare-chocs avant pour la protection et l''esthétique du véhicule.', '1', '014', '002', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00323', 'Remplacement du solénoïde de contrôle de purge EVAP', 'Remplacement du solénoïde pour un contrôle optimal des émissions de vapeur.', '4', '043', '001', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00324', 'Remplacement du tendeur de la courroie d''entraînement', 'Remplacement du tendeur de courroie pour maintenir une tension correcte et éviter l''usure prématurée.', '4', '045', '008', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00325', 'Remplacement du tendeur de la courroie de distribution', 'Remplacement du tendeur de la courroie de distribution pour maintenir une tension adéquate.', '4', '045', '008', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00326', 'Remplissage du liquide de lave-glace', 'Remplissage du réservoir de liquide de lave-glace pour garantir un nettoyage efficace du pare-brise.', '0', '002', '035', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00327', 'Remplissage du liquide de refroidissement (HOAT)', 'Remplissage du liquide de refroidissement HOAT (Hybrid Organic Acid Technology) dans le moteur.', '5', '053', '999', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00328', 'Remplissage du liquide des émissions diesel', 'Remplissage du liquide des émissions diesel pour maintenir le fonctionnement du système de contrôle des émissions.', '4', '043', '007', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00329', 'Remplissage du liquide du différentiel', 'Remplissage du liquide du différentiel pour assurer un fonctionnement adéquat du différentiel.', '5', '053', '999', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00330', 'Réparation du rétroviseur extérieur', null, '0', '002', '010', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00331', 'réparation quaie de chargement', null, '9', '999', null, 'curatif', '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00332', 'RIMULA EXTRA 15W40209L', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00333', 'service HSE', null, '9', '999', null, null, '{}'::text[], 1, 'fleetio', true),
  ('TCH-2026-00334', 'Suspension avant (Divers)', 'Entretien divers et vérifications de la suspension avant pour garantir son bon fonctionnement.', '1', '016', '001', 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00335', 'Test de l''alternateur', 'Vérification du fonctionnement de l''alternateur pour s''assurer qu''il charge correctement la batterie.', '3', '031', '001', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00336', 'TOLES', null, '0', '002', null, null, '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00337', 'Transmission Automatique (Divers)', 'Divers travaux ou vérifications liés à la transmission automatique non spécifiés.', '2', '027', null, 'curatif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00338', 'Transmission Oil Replacement', null, '2', '026', null, null, '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00339', 'Vidange et remplissage de l''ensemble essieu arrière', 'Vidange du liquide et remplissage de l''ensemble essieu arrière pour garantir un fonctionnement optimal.', '2', '022', '007', 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00340', 'Vidange et remplissage de l''ensemble essieu moteur', 'Cette tâche consiste à vidanger le liquide du différentiel de l''essieu moteur, puis à le remplir avec un nouveau fluide.', '2', null, null, 'preventif', '{}'::text[], 1, 'fleetio', false),
  ('TCH-2026-00341', 'Vidange et remplissage du liquide de transmission', 'Vidange et remplissage du liquide de transmission pour maintenir le bon fonctionnement de la boîte de vitesses.', '5', '053', '999', 'preventif', '{}'::text[], 1, 'fleetio', false)
on conflict do nothing;

select count(*) as taches, count(*) filter (where a_classer) as a_classer, sum(utilisations) as utilisations from tache_service;
