-- ============================================================================
-- SEDIMA Parc — location et transport réels : les frais de mission et de péage.
--
-- **Ce n'est pas une migration.** Chargement tiré du classeur d'extraction des
-- bons de commande du dossier DO — famille « Location & transport », que le
-- chargement de la maintenance avait laissée de côté.
--
-- 25 frais qui ne sont pas des prestations de transport mais des charges du
-- parc. Ils n'ont pas de véhicule nommé et citent donc leur bénéficiaire, ce
-- que la contrainte `depense_tracable` exige : une dépense sans véhicule doit
-- rester traçable.
--
-- REJOUABLE : `on conflict do nothing`. À jouer **dans l'ordre des fichiers**,
-- les transporteurs d'abord.
-- ============================================================================

insert into depense (numero, prestataire_id, date, poste, libelle, montant, beneficiaire, origine, justificatif, reference) values
  ('DEP-T-00001', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2024-04-08', 'peage', 'FRAIS DE PASSAGES DU PÉAGE DES VÉHICULES LIVRAISONS - FACTURE | DU MOIS DE JANVIER | FACTURE N: N301324010663 | EIFFAGE CONCESSION | SORTIE 9- RUFISQUE', 922100, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC16186'),
  ('DEP-T-00002', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'FOURNISSEURSDIVERS' limit 1), '2024-05-07', 'peage', 'SERVICE PARC | FRAIS DE MISSION POUR LA LIVRAISON DE POULETS A ZIGUINCHOR | CHÈQUE AU NOM DE MORY DJITE', 150000, 'FOURNISSEURS DIVERS', 'bon-de-commande', true, 'BC16323'),
  ('DEP-T-00003', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2024-06-10', 'peage', 'FRAIS DES PASSAGE PÉAGE DU MOIS D''AVRIL | FACTURES : N301324040629 | SECCA | SORTIE 9 PEAGE RUFISQUE', 1294800, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC16521'),
  ('DEP-T-00004', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SPEEDY' limit 1), '2024-09-05', 'peage', 'SERVICE PARC | REGULARISATION DES FACTURES DE SPEEDY PEAGE POUR LES | ENTRETIENS DES VEHICULES DE LA FLOTTE SEDIMA | SPEEDY PEAGE', 533499, 'SPEEDY', 'bon-de-commande', true, 'BC16937'),
  ('DEP-T-00005', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2024-10-24', 'peage', 'SERVICE PARC | PASSAGE RAPIDO MOIS DE SEPTEMBRE 2024 DES VEHICULES DE | LIVRAISON', 1008900, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC17206'),
  ('DEP-T-00006', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-02-07', 'peage', 'SERVICE PARC | FACTURE POUR LES PASSAGES SUR L''AUTOROUTE | FACTURE DÉCEMBRE 2024 | SECAA EIFFAGE', 1327400, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC17709'),
  ('DEP-T-00007', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-02-27', 'peage', 'SERVICE PARC | PASSAGE RAPIDO DES VEHICULES DE LIVRAISON POUR LE MOIS DE | JANVIER 2025', 1291600, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC17857'),
  ('DEP-T-00008', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-05-05', 'peage', 'SERVICE PARC | PASSAGE PEAGE DES VEHICULES DE LIVRAISONS POUR LE MOIS DE | MARS 2025', 1162600, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC18135'),
  ('DEP-T-00009', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-05-27', 'peage', 'FACTURE SECAA PASSAGE RAPIDO DU MOIS DE FEVRIER 2025.', 1202700, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC18282'),
  ('DEP-T-00010', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-06-23', 'peage', 'SERVICE PARC | PAYEMENT PASSAGE RAPIDO POUR LE MOIS D''AVRIL 2025 DES | VEHICULES DE LIVRAISON | SECAA', 1207300, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC18436'),
  ('DEP-T-00011', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-07-09', 'peage', 'SERVICE PARC | PASSAGE PEAGE POUR LES VEHICULES DE LIVRAISON MAI 2025 | EIFFAGE SENEGAL', 1339499, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC18547'),
  ('DEP-T-00012', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-07-22', 'peage', 'SERVICE PARC | PASSAGE PEAGE POUR LES VEHICULES DE LIVRAISON JUIN 2025 | EIFFAGE SENEGA', 1202900, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC18624'),
  ('DEP-T-00013', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-08-04', 'peage', 'SERVICE PARC | FACTURE PASSAGE PEAGE DES VEHICULES DE LIVRAISON POUR LE MOIS | DE FEVRIER 2025', 1202700, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC18721'),
  ('DEP-T-00014', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-09-01', 'peage', 'SERVICE PARC | PASSAGE PEAGE DES VEHICULES DE LIVRAISONS DE POUR LE MOIS DE | JUILLET 2025 | EIFFAGE SENEGAL', 1323300, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC18839'),
  ('DEP-T-00015', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-09-23', 'peage', 'SERVICE PARC | PASSAGE PEAGE POUR LES VEHICULES DE LIVRAISON POUR LE MOIS DE | AOUT 2025 | EIFFAGE SENEGAL', 1211900, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'BC18961'),
  ('DEP-T-00016', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'FOURNISSEURSDIVERS' limit 1), '2025-11-19', 'peage', 'FRAIS MISSION ZIGUINCHOR AA 565 GA ET AA 783 BN', 236000, 'FOURNISSEURS DIVERS', 'bon-de-commande', true, 'CMD2-25110262'),
  ('DEP-T-00017', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2025-12-23', 'peage', 'PASSAGE PEAGE NOVEMBRE 2025', 1294400, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'CMD2-25120345'),
  ('DEP-T-00018', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2026-02-13', 'peage', 'PASSAGE PEAGE VEHICULE LIVRAISON DECEMBRE 2025', 1341600, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'CMD2-26020230'),
  ('DEP-T-00019', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2026-03-02', 'peage', 'PASSAGE PEAGE MOIS DE JANVIER 2026 POUR LES VEHICULES DE LIVRAISON', 1089900, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'CMD2-26030023'),
  ('DEP-T-00020', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2026-04-03', 'peage', 'PASSAGE PEAGE VEHICULES LIVRAISON POUR LE MOIS DE FEVRIER 2026', 1190801, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'CMD2-26040057'),
  ('DEP-T-00021', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'FOURNISSEURSDIVERS' limit 1), '2026-04-10', 'peage', 'FRAIS DE ROUTE MISSION KEDOUGOU DU 11-04 AU 13-04-2026', 100000, 'FOURNISSEURS DIVERS', 'bon-de-commande', true, 'CMD2-26040147'),
  ('DEP-T-00022', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'FOURNISSEURSDIVERS' limit 1), '2026-04-24', 'peage', 'FRAIS DE ROUTE LIVRAISON POULETS FRAIS A KEDOUGOU PAR MORY DJITE DU 21 AU | 24/04/2026 ET DU 25 AU 27/', 200000, 'FOURNISSEURS DIVERS', 'bon-de-commande', true, 'CMD2-26040367'),
  ('DEP-T-00023', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2026-05-08', 'peage', 'FACTURE PASSAGE PEAGE DES VEHICULES DE LIVRAISON POUR LE MOIS DE MARS | 2026', 1430900, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'CMD2-26050139'),
  ('DEP-T-00024', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2026-06-16', 'peage', 'PASSAGE PEAGE DES VEHICULES DE LIVRAISON POUR LE MOIS DE AVRIL 2026', 1465000, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'CMD2-26060250'),
  ('DEP-T-00025', (select id from prestataire where upper(regexp_replace(raison_sociale, '[^A-Za-z0-9]', '', 'g')) = 'SECAAEXSENAC' limit 1), '2026-06-29', 'peage', 'FACTURE PASSAGE PEAGE VEHICULE LIVRAISON POUR LE MOIS DE MAI 2026', 1167300, 'SECAA (ex SENAC)', 'bon-de-commande', true, 'CMD2-26060424')
on conflict (numero) do nothing;
